### ISSUE TITLE
algorithm-marked-outlier and manually-marked-outlier not imported by Movebank

### ISSUE THREAD

**Issue by peterdesmet** [inbo/bird-tracking#105]
1. Upload [sample GPS data](https://github.com/inbo/bird-tracking/blob/master/data/processed/MH_WATERLAND/movebank_gps_data_586.csv) for 586 as custom GPS data to Movebank
2. Map all fields, including `algorithm-marked-outlier` (4 `TRUE`, rest `FALSE`) and `manually-marked-outlier` (all `FALSE`)
3. Import data
4. Go to "Data set editor" (Event editor)
5. Both `outlier` fields are empty, and outliers are thus not marked (e.g. the one for timestamp `2013-06-05 12:49:03.000`)

## Probably causes

cc @sarahcd

### Algorithm marked outlier not available for upload

I read somewhere that `algorithm-marked-outlier` is only available for Argos data, so this might be by design, but:

1. It is not documented as such in the [attributes list](https://www.movebank.org/node/2381#outlier_algorithm)
2. It is available for mapping in the upload tool

### Manually marked outlier not available for upload

I also retried with mapping the values of `algorithm-marked-outlier` (which contains 4 `TRUE`)  to `manually-marked-outlier`, but that field remained empty in the Event editor.

### TRUE/FALSE issue

My values are marked with uppercase `TRUE`/`FALSE`, which might cause an issue, but I mapped to `true`/`false` in the upload tool + validation returned `OK`

**Comment by sarahcd** [comment]
algorithm-marked-outlier should not be available for mapping in the GUI, I've reported this as a bug.

Here's the definition: "Identifies events marked as outliers using a user-selected filter algorithm in Movebank. Outliers have the value TRUE." This attribute is created and filled using [filters](https://www.movebank.org/node/33529) in the Event Editor. So if users imported values from elsewhere they might accidentally overwrite them.

If you want to import outliers that have been flagged by some other algorithm (i.e. it doesn't seem right to store them as "manually marked") I'd recommend mapping them as import-marked-outlier. This shows up in the import gui under "other attributes". It's pretty new and I haven't added it to the dictionary yet but will do that tomorrow!

**Comment by peterdesmet** [comment]
Thanks! Is import-marked-outlier taken into consideration (just like algorithm and manually marked) for what Movebank considers an outlier and thus not visible? I would like that. 😊

**Comment by sarahcd** [comment]
Import marked outlier is in the attribute dictionary now. Yes, the "visible" attribute incorporates all the outlier-related attributes and defines what locations are visible on the map.
