### ISSUE TITLE
Barometric height vs altitude

### ISSUE THREAD

**Issue by peterdesmet** [inbo/bird-tracking#108]
Is Movebank `barometric height` equal to UvA-BiTS `altitude`?

https://github.com/inbo/bird-tracking/blob/25495a0461f72dc69c7cf063779c1f5030aa2ba6/sql/movebank_gps_data.sql#L42

Movebank `barometric height` is defined as (https://www.movebank.org/node/2381#data):

> Altitude estimated by a barometric pressure sensor on the tag.
> example: 179
> units: m
> same as: bar:barometric height

UvA-BiTS `altitude` is defined as (https://wiki.pubserv.e-ecology.nl/wiki/index.php/DB_Views_2015#gps.ee_tracking_speed_limited):

> Altitude above sea level measured by GPS tag in meters

@Wouter-Vansteelant @jshamoun: it is the altitude **measured by the tag**: is that a "barometric pressure sensor" as per Movebank definition?

**Comment by peterdesmet** [comment]
Thanks, so `altitude` aligns better with:

> **height above ellipsoid**: The estimated height above the ellipsoid returned by the GPS unit. (If altitudes are calculated as height above mean sea level, use height above mean sea level.)
> example: 24.8
> units: meters

or:

> **height above mean sea level**: The estimated height of the tag above mean sea level returned by the GPS unit. (If altitudes are calculated as height above an ellipsoid, use height above ellipsoid.)
> example: 34
> units: meters
> same as: height above msl

Which one would you choose?

---

Agree, I only see the field `pressure` in `gps.ee_tracking_speed_limited` which isn't populated for our tags. I don't see a field with the height from that pressure.

---

> whether the barometric height in Movebank is calculated by Movebank itself or by tag providers.

It is not calculated by Movebank itself (ping @sarahcd) but by the tag provider, i.e. it is one of the many attributes you can map data to when uploading data to Movebank

**Comment by sarahcd** [comment]
Correct, Movebank doesn't calculate this. From your description I'd say the height-amsl is the better fit as it defines the datum. Also EnvDATA can use values stored here to [annotate weather data based on altitude](https://www.movebank.org/node/6400#interpolation_vertical).

**Comment by peterdesmet** [comment]
Based on discussions `barometric-height` is not mapped (that data is not available)

https://github.com/inbo/bird-tracking/blob/daae6e9ac0934add7d828720bdc6eb5682903b40/sql/movebank_gps.sql#L63-L64

And the GPS measured altitude is mapped to `height-above-mean-sea-level`:

https://github.com/inbo/bird-tracking/blob/daae6e9ac0934add7d828720bdc6eb5682903b40/sql/movebank_gps.sql#L105-L107
