### ISSUE TITLE
H173481: 4 records incorrectly with manually-marked-outlier

### ISSUE THREAD

**Issue by peterdesmet** [inbo/bird-tracking#114]
For Movebank study `604806671` (`MH_WATERLAND`), individual H173481, 4 records have `manually-marked-outlier = TRUE`, even though the data were all uploaded with `manually-marked-outlier = FALSE`. @sarahcd, any idea why these are marked that way in Movebank? I can't recall setting those in the Event editor, which I now can't open because the number of records is too high.

**Comment by peterdesmet** [comment]
My mistake, I didn't notice it was actually mapping to `manually-marked-outlier`. It looks though that you can map 2 source columns to the same Movebank column:

<img width="378" alt="Screenshot 2019-09-06 at 14 49 50" src="https://user-images.githubusercontent.com/600993/64429153-ab1d6880-d0b5-11e9-83b7-8faad23342da.png">

**Comment by peterdesmet** [comment]
Data re-uploaded to Movebank: fixed.

**Comment by sarahcd** [comment]
I just tried to reproduce this double mapping issue but after mapping the column once, it is disabled in the list of attributes. Did that successfully import after being mapped like that? In any case I'll keep an eye out for it.

**Comment by peterdesmet** [comment]
It did import successfully, which is why I ended up with 4 outliers (that originated from a column I wasn’t supposed to map).

Maybe it is possible to reproduce the double mapping by having the columns named algorithm-marked-outlier and manually-marked-outlier in the source data? 🤷‍♂️
