### ISSUE TITLE
5446465 has records without coordinates in H_GRONINGEN

### ISSUE THREAD

**Issue by peterdesmet** [inbo/bird-tracking#115]
1 individual in H_GRONINGEN has records with empty coordinates:

individual | records
--- | ---
5446465	| 84

I haven't encountered this yet in UvA-BiTS. Would be good to ask the authors why this happened.

**Comment by milotictanja** [comment]
I downloaded the data from the UvA-BiTS database, but for some reason the number of empty coordinates is slightly different:

individual | records
--------- | ------------
5325667 | 0
5446465 | 84

Remarkably, all 84 NA's for individual 5446465 were recorded during the first tracking month (10-28 May 2012). I asked the data owners if they have a possible explanation for this phenomenon.

**Comment by peterdesmet** [comment]
I am going to remove this records from the query: the only info they have is temperature.

**Comment by peterdesmet** [comment]
Done in , 5446465  now has 178821 (9) records.
