### ISSUE TITLE
Upload accelerometer data for harrier datasets

### ISSUE THREAD

**Issue by peterdesmet** [inbo/bird-tracking#117]

**Comment by peterdesmet** [comment]
No data for `MH_WATERLAND`, but it is available for the other two datasets. @milotictanja can you check if we can publish these data?

key_name | device_info_serial | acc
--- | --- | ---
H_GRONINGEN | 291 | yes
H_GRONINGEN | 634 | yes
H_GRONINGEN | 6064 | yes
H_GRONINGEN | 6065 | yes
MH_ANTWERPEN | 1603 | yes
MH_ANTWERPEN | 6329 | yes
MH_ANTWERPEN | 6330 | yes
MH_WATERLAND | 586 | no
MH_WATERLAND | 610 | no
MH_WATERLAND | 623 | no
MH_WATERLAND | 630 | no
MH_WATERLAND | 6058 | no
MH_WATERLAND | 6059 | no

**Comment by milotictanja** [comment]
We may publish the accelerometer data from the MH_ANTWERPEN dataset, but I am still waiting for a response of the data owners of the H_GRONINGEN dataset

**Comment by peterdesmet** [comment]
All numbers are now ok. @milotictanja can you ping again about uploading the data to Movebank.

**Comment by peterdesmet** [comment]
All acceleration data are now uploaded to movebank.

**Comment by peterdesmet** [comment]
Reopened because wrong timestamp field was used.

**Comment by peterdesmet** [comment]
Solved.
