### ISSUE TITLE
tag-readout-method not saved

### ISSUE THREAD

**Issue by peterdesmet** [inbo/bird-tracking#120]
@sarahcd, in my ref data mapping I have set `tag-readout-method` to `other wireless`. This seemed to work fine in the mapping, but I notice that all the data have been saved with empty values for that field. I have since manually corrected it.

Maybe it is because the value in the DB is `other-wireless` (with dash instead of space). In any case, would be good to warn the user the value doesn't match the vocab.

**Comment by sarahcd** [comment]
You're correct that for controlled-list values with multiple words, if the values in the file contain a space, Movebank will not make a guess at the mapping and the user will need to define it, e.g. mapping from "other wireless" > "other-wireless". In the example below this hasn't been mapped and the value of "other wireless" is shown as not set: 

![image](https://user-images.githubusercontent.com/15783614/66407873-f203c400-e9bb-11e9-9a08-34775a572a36.png)

Click on the dropdown list to map this value to "other-wireless". If some values remain not set after saving the mapping, the fields will show as empty in the preview if they are present in the top rows of the file:

![image](https://user-images.githubusercontent.com/15783614/66408080-48710280-e9bc-11e9-8594-71b7c84d1691.png)

There's no option to skip the mapping of controlled list variables, i.e. there is always a step where the user checks and has the chance to complete/correct the guesses Movebank makes with the mapping. That said I agree a warning message if there are unmapped rows could be helpful.

**Comment by peterdesmet** [comment]
Ok, I think it would mostly help that the controlled vocab at https://www.movebank.org/node/2381 has `other-wireless` (without space). Idem for other vocab values with spaces.

I'm going to update my SQL script to output it as `other-wireless`, so it maps automatically.
