### ISSUE TITLE
Allow to map unknown sex in Movebank

### ISSUE THREAD

**Issue by peterdesmet** [inbo/bird-tracking#121]
Answer by @sarahcd:

> Thanks Peter, I agree we ought to allow sex=u. I put it on a list of proposed additions for an upcoming round of attribute changes.

Once that is done, this query should be updated:

https://github.com/inbo/bird-tracking/blob/daae6e9ac0934add7d828720bdc6eb5682903b40/sql/movebank_ref.sql#L62-L67

Note that this is not an issue for the harrier datasets, as all sexes are known. It will be an issue for the gulls + oystercatchers

**Comment by peterdesmet** [comment]
Does not occur in HG_OOSTENDE. It does in:

LBBG_ZEEBRUGGE: L910466
O_WESTERSCHELDE: L918404, L922112

**Comment by sarahcd** [comment]
FYI, u can be mapped to animal-sex now. This will be updated in the vocabulary ASAP, but in the meantime it works in imports and on the website.

**Comment by peterdesmet** [comment]
Thanks, our two datasets have been uploaded to make use of it.
