### ISSUE TITLE
4 birds with lots of data before start of track sessions

### ISSUE THREAD

**Issue by peterdesmet** [inbo/bird-tracking#129]
There are 4 herring gulls for which there is a lot of acceleration data (more than 7 days) before the start of the tracking session:

ring | device | session start | acceleration start | diff days
--- | --- | --- | --- | ---
H905081 | 6248 | 2018-06-06 12:00:00 UTC | 2017-08-22 08:10:42 UTC | 288
H905082 | 6246 | 2018-06-06 12:00:00 UTC | 2017-08-22 07:56:49 UTC | 288
H905083 | 6249 | 2018-06-06 12:00:00 UTC | 2017-08-22 07:55:37 UTC  | 288
H905201 | 6187 | 2016-05-23 12:00:00 UTC | 2015-06-09 06:15:16 UTC | 349

@EricStienen can you verify these track sessions start dates are correct?

**Comment by EricStienen** [comment]
These trackers were used on captive birds in the VOC to annotate behaviour before apllying them to wild birds.  Only acc-data after session start should be used!

**Comment by peterdesmet** [comment]
Aha, then it makes sense why there is so much data. 👌Only data within track session will be used (as always).
