### ISSUE TITLE
Area for bird L178426?

### ISSUE THREAD

**Issue by peterdesmet** [inbo/bird-tracking#138]
All birds have a region/breeding area in their `track_session_remarks`, except for bird `L178426` `EAVS` (blue dot below). Where was it captured/breading?

<img width="455" alt="Screenshot 2020-03-19 at 17 18 42" src="https://user-images.githubusercontent.com/600993/77089378-0dacd500-6a06-11ea-925d-54d34ba2663a.png">

**Comment by Geert282** [comment]
Doel

**Comment by peterdesmet** [comment]
👍 Updated in database
