### ISSUE TITLE
O_WESTERSCHELDE: data for 7 birds only + confirm end date

### ISSUE THREAD

**Issue by peterdesmet** [inbo/bird-tracking#139]
tag-id | animal-id | Number_of_Rows | timestamp_min | timestamp_max | acc record
--- | --- | --- | --- | --- | ---
5622 | L918403 | 192 | 2018-05-25T16:11:37Z | 2018-05-26T16:02:36Z | 3815
5645 | L922102 | 5782 | 2018-05-31T16:45:26Z | 2018-07-12T13:46:26Z | 748365
5651 | L922103 | 10084 | 2018-05-31T16:13:14Z | 2019-05-11T13:31:07Z | 517477
5672 | L922107 | 7604 | 2018-06-11T19:01:21Z | 2018-09-26T03:45:56Z | 75911
5742 | L918401 | 5815 | 2018-05-24T18:10:51Z | 2018-12-15T22:57:09Z | 83631
5743 | L918405 | 30071 | 2018-05-28T16:02:53Z | 2018-10-30T21:41:26Z | 0
5745 | L178426 | 6157 | 2019-06-20T15:48:53Z | 2019-07-18T18:13:00Z | 121638

- [x] I noticed that of the 13 tags birds, with 7 have associated gps data. Is this correct?
- [x] The data covers 2018 and 2019. I propose to publish both years.
- [x] Can more data from 2019 (or 2020) be expected? E.g. from birds with active trackers that are not read out?
- [x] Why does bird L918405 not have any associated acceleration data? Was it not activated for this tracker? **Unknown**

**Comment by peterdesmet** [comment]
Map (not the full extend):

<img width="683" alt="Screenshot 2020-03-21 at 15 52 28" src="https://user-images.githubusercontent.com/600993/77229095-057ea200-6b8c-11ea-8ab4-ed705262312b.png">

**Comment by Geert282** [comment]
L918405: acc-data not registrated ... unknown reason
More data can be expected but for the moment Corona thinks otherwise

Will the map show the data for France as well ?

**Comment by peterdesmet** [comment]
Yes, the map will show the full extend of the data, this was just a cropped screenshot. I will upload data for 2018 and 2019. Updated data (for e.g. 2019) and new data (for 2020) can always be uploaded later.
