### ISSUE TITLE
O_WESTERSCHELDE: is more know about the deployment-end-type

### ISSUE THREAD

**Issue by peterdesmet** [inbo/bird-tracking#140]
Is more known about the end of the track session for (some of) these birds? If so, we should populate it in track-session-remarks.

**Comment by Geert282** [comment]
Meaning ? Something like:

5622: battery too low
5743: we removed antenna at winter location
...

**Comment by peterdesmet** [comment]
Yes, indeed. For the western marsh harriers in Waterland, we have e.g.:

```
Waterland-Oudeman | Assumed dead.
Waterland-Oudeman | Tracker reused from L143467, assumed dead.
Waterland-Oudeman | Found dead on 2016-03-31 in Alps, last active day is 2016-03-25. Tracker reused for H185298.
```

The first part is the name of the township where the bird was captured (see #138), the second part the status of the bird/session (not available for all birds). This information goes to Movebank as `deployment-comments`. If the word "dead" appears, this will also be indicated in `deployment-end-type` (i.e. the reason is session was stopped).

The comments for all birds can be added to this issue (with the tag id) and I will update it in the database. Or if you prefer, you can add it there directly.

**Comment by peterdesmet** [comment]
Geert:

```
5742L Verrebroek | found dead, last data on 15/12/2018
5670L Verrebroek | returned 2019 but data not downloaded
5622L Doel | returned 2019 and data downloaded until 26/05/2018
5658L Kemzeke | no data
5743L Doel | alive in 2019, stayed at winter-location, no data downloaded
5741L Doel | no data
5744L Doel | no data
5645L Zaffelare | returned 2019 and data downloaded until 12/07/2018
5651L Wachtebeke | returned 2019 and data downloaded until 11/05/2019
5672L Evergem | found dead, last data on 26/09/2018
5624L Oostakker | returned 2019 but transmitter not responding
5653L Kallo| no data
5745L Doel | left breeding area on last day of data: 18/07/2019
```

Reworked to:

```
5742L Verrebroek | Found dead on **xxxx-xx-xx in xx**, last active day is 2018-12-15.
5670L Verrebroek | Returned in 2019, no tracking data received.
5622L Doel | Returned in 2019, data downloaded until 2018-05-26.
5658L Kemzeke | No tracking data received.
5743L Doel | Alive in 2019, stayed at winter-location, **data downloaded until 2018-10-30**.
5741L Doel | No tracking data received.
5744L Doel | No tracking data received.
5645L Zaffelare | Returned in 2019, data downloaded until 2018-07-12.
5651L Wachtebeke | Returned in 2019, data downloaded until 2019-05-11.
5672L Evergem | Found dead on **xxxx-xx-xx in xx**, last active day is 2018-09-26.
5624L Oostakker | Returned in 2019, tracker not responding.
5653L Kallo| No tracking data received.
5745L Doel | Left breeding area on last day of data: 2019-07-18.
```

**Comment by peterdesmet** [comment]
@Geert282 :

- Do you know when and where you found dead 5742L and 5672L?
- For 5743L you meant "no data downloaded in 2019"? There is data until 2018-10-30

**Comment by Geert282** [comment]
5742 found dead at Tholen (Nl) on 2018-08-24
5672 found dead at NP Baie de Somme (Fr) on 2019-02-05

5743 data downloaded at winter location until 2018-10-30

**Comment by peterdesmet** [comment]
5742 was found dead in 2018? So all remaining data is probably non-biological data. Will look into this.

**Comment by Geert282** [comment]
indeed, the transmitter was just transported to Texel

**Comment by peterdesmet** [comment]
The bird was active in Sint-Maartensdijk on 2018-04-24: was it there where you found it ("Tholen")?

**Comment by peterdesmet** [comment]
Updated to:

> Found dead in Sint Maartensdijk (NL) on 2018-08-24, last active day is 2018-08-23.
