### ISSUE TITLE
Updated project names in UvA-BiTS

### ISSUE THREAD

**Issue by peterdesmet** [inbo/bird-tracking#141]
The project descriptions in UvA-BiTS are now the same as the public datasets (without the project code, which is in `key_name`):

```
Herring gulls (Larus argentatus, Laridae) breeding at the southern North Sea coast (Belgium)
Lesser black-backed gulls (Larus fuscus, Laridae) breeding at the southern North Sea coast (Belgium and the Netherlands)
Western marsh harriers (Circus aeruginosus, Accipitridae) breeding near the Belgium-Netherlands border
Western marsh harriers (Circus aeruginosus, Accipitridae) breeding near Antwerp (Belgium)
```

For reference, the previous titles were:

```
Habitat use of Herring Gulls breeding at the southern North Sea coast (mainly Ostend)
Habitat use of Lesser Black-backed Gulls breeding at the southern North Sea coast (mainly Zeebrugge and Vlissingen)
Habitat use of Western Marsh Harriers breeding near the Belgium-Netherlands border (Saeftinghe-region)
Habitat use of Western Marsh Harriers breeding near the Belgium-Netherlands border (Waterland-Oudeman)
```

The project title for `H_GRONINGEN` is not updated, because I don't have the rights.

**Comment by peterdesmet** [comment]
The `O_WESTERSCHELDE` project description is currently:

```
Habitat use of East-Flanders breeding Oystercatchers wintering on the Western Scheldt
```

But that will be updated similarly.

**Comment by peterdesmet** [comment]
I suggest:

> O_WESTERSCHELDE - Eurasian oystercatchers (Haematopus ostralegus, Haematopodidae) wintering on the Western Scheldt and breeding in East-Flanders (Belgium)

**Comment by Geert282** [comment]
Habitat use of Eurasian oystercatchers (Haematopus ostralegus, Haematopodidae) breeding in East-Flanders (Belgium) in the non-breeding season.

the research topic was WS but the outcome of the data was much broader

**Comment by peterdesmet** [comment]
1. I will have to adapt that a little bit, so it follows the same format as the titles above (so starting with the scientific name and dropping "habitat use of".
2. "breeding in East Flanders (Belgium) _in the non-breeding season_" seems to be a contradiction. Can you clarify?
3. It might be good to mention the Western Scheldt somewhere, so there is a link with the project code, but not required.

**Comment by Geert282** [comment]
breeding in East Flanders (Belgium) and staying on the Wester Scheldt in the non-breeding season

laat het dan maar zoals hierboven. de data komen ook uit Frankrijk en Oosterschelde
ze broeden in het binnenland en daarbuiten (van juli tot maart) zitten ze in estuarien gebied

**Comment by Geert282** [comment]
dus wat ik wou zeggen is dat het veel langer is dan de winter alleen

**Comment by peterdesmet** [comment]
Ok, dan hou ik het kort en bondig op:

> O_WESTERSCHELDE - Eurasian oystercatchers (Haematopus ostralegus, Haematopodidae) breeding in East Flanders (Belgium)

Cf

> MH_ANTWERPEN - Western marsh harriers (Circus aeruginosus, Accipitridae) breeding near Antwerp (Belgium)

**Comment by peterdesmet** [comment]
Updated in UvA-BiTS as well
