### ISSUE TITLE
Gull Tony: juvenile + end date

### ISSUE THREAD

**Issue by peterdesmet** [inbo/bird-tracking#144]
@EricStienen, regarding gull "Tony" `H908157`/`6321`:

- In the Excel it is indicated he is `5kJ`. I assume that is juvenile? And so far the only juvenile bird we have tracked with UvA-BiTS?
- You also mentioned he was "Found dead 2019-10-04". Do you have more information about cause, location, and until when his tracking session is valid?

**Comment by EricStienen** [comment]
5kJ (or 5cy = 5 calendar years) seems right. The bird almost fully looked like an adult but with a few brown feathers in its tail. However, it was not the typical appearance of a 4cy. So best expert judgement is that is a bird in its fifth calendar year.

The bird was found dead on 04/10/2019 in Lombardsijde at the beach. Finder stetes that it was dead for a while, but without indication how many days "a while" is.

**Comment by peterdesmet** [comment]
Updated in database. Now states in track session remarks:

> OOST_MIJN | life_stage: 5cy | Found dead on beach in Lombardsijde (BE) on 2019-10-04, last active day is 2019-07-22.

2019-07-22 is the last active day in the data, when it was near the vismijn. Not sure how it moved to Lombardsijde, but if it died shortly after 2019-07-22, then it was dead for over 2 months.
