### ISSUE TITLE
Add vernacular name and breed

### ISSUE THREAD

**Issue by peterdesmet** [inbo/bird-tracking#155]
@sarahcd, for the Digitanimal trackers we are using to follow livestock in nature reserves, the scientific name is not sufficient to identify the animal. We also need:

- vernacular name: e.g. `Equus caballus` could be horse or pony
- animal breed: `West-vlaams roodbont`, `Galloway`, `Koniks`

I've currently mapped this information into `animal-comments`:

animal-taxon | animal-comments
--- | ---
Bos taurus | rund: Aberdeen
Bos taurus | rund: Galloway
Bos taurus | rund: Oost-Vlaams Witrood
Bos taurus | rund: West-vlaams roodbont
Equus asinus | ezel: Cotentin Flamande
Equus caballus | paard: huis-tuin-keuken versie
Equus caballus | paard: Konik
Equus caballus | pony: Fjord

But I was wondering if there is (a use case for) a better field?

**Comment by sarahcd** [comment]
What about this? 
http://vocab.nerc.ac.uk/collection/MVB/current/MVB000025/

**Comment by peterdesmet** [comment]
That could work. I assumed this needing to be a scientific name, but the definition leaves it open for it not to be.
