### ISSUE TITLE
Split confined birds at OOST_VOC in two deployments

### ISSUE THREAD

**Issue by peterdesmet** [inbo/bird-tracking#157]
5 LBBG_JUVENILE birds have release_location `VOC_OOST`, but their track session start is earlier than their actual release date. Likely to also have records for the movements at VOC?

tag id | track_session_start_date | release date
--- | --- | ---
193965 | 2020-07-24 18:00:00 | 2020-09-11
193968 | 2020-09-04 18:00:00 | 2020-09-11
193973 | 2020-07-24 18:00:00 | 2020-09-11
193985 | 2020-07-24 18:00:00 | 2020-09-11
200551 | 2020-07-24 18:00:00 | 2020-09-11

I think it would be better to split those into two deployments, e.g.:

tag id | track_session_start_date | release date | manipulation type
--- | --- | --- | ---
193965 | 2020-07-24 18:00:00 | 2020-09-11 | confined
193965 | 2020-09-11  | - | ?

@EricStienen:

- [x] Where the animals indeed confined at VOC until they were released and do we want those tracking data?
- [x] Where were the animals released? At the VOC site itself?
- [ ] What would be the best manipulation type description when they were released:

```
confined = The animal's movement was restricted to within a defined area
none = The animal received no treatment other than the tag attachment
relocated = The animal was released from a site other than the one at which it was captured
manipulated other = The animal was manipulated in some other way, such as a physiological manipulation
```

**Comment by EricStienen** [comment]
All 5 trackers were fitst used on juvenile birds in Zeebrugge, that where however predated by a fox soon after fledging. Next these trackers were deployed to juvenile that where experimentally raised in the VOC. Release date 11-09-2021 should therefore be the start date of the new individuals. However , the data of the individuals that were initially equiped with the loggers should not be lost as it might give important information on their postfleding behaviour (although short).  Could you split the data into é differnt parts?

**Comment by peterdesmet** [comment]
Metadata are now split into two deployments (in Ornitela metadata spreadsheet): one for juvenile (found dead) and one for reuse on bird raised in VOC. For the second bird, deployment starts _after_ release from VOC. Since the bird was not confined, but otherwise still manipulated, the type is set to `manipulated other` in 71d677e
