### ISSUE TITLE
Create study for UGent HG trackers `HG_JUVENILE`

### ISSUE THREAD

**Issue by peterdesmet** [inbo/bird-tracking#188]
Info to be provided by @ReinoudAllaert

**Comment by ReinoudAllaert** [comment]
Metadata for the study as required for movebank:
[HG_movebank_meta.pdf](https://github.com/inbo/bird-tracking/files/9173496/HG_movebank_meta.pdf)

**Comment by peterdesmet** [comment]
Thanks! Some updates:

1. I've changed `haid-raised` to `handraised` in the title, as that seems to be the more common spelling.
2. I've rephrased the description somewhat, to:

> _HG_JUVENILE - Juvenile herring gulls (Larus argentatus, Laridae) hatched and handraised in Ostend (Belgium)_ is a bird tracking dataset published by the [Cognition, Behavior, and Ecology lab](https://cobe.ugent.be/) at Ghent University. It contains animal tracking data for the project/study **HG_JUVENILE**, using trackers developed by Interrex (http://www.interrex-tracking.com/). The study has been operational since 2022. In total 60 individuals of European herring gull (_Larus argentatus_) have been tagged and released in the IJzermonding, Nieuwpoort (Belgium). All individuals were raised from egg by Ghent University researchers at the [Wildlife Rescue Center](https://www.vogelopvangcentrum.be/) in Ostend and completed several cognitive and behavioural tests when approximately three weeks old. The main goal of the study is to link cognitive performance in the lab to behaviour in the wild. Data are automatically synced with Movebank and from there periodically archived on Zenodo (see https://github.com/inbo/bird-tracking).

3. I typically include myself as author for the tracking datasets I contribute to. Ok if I update the citation to:

>  Allaert RA, Stienen EWM, Lens L, Desmet P, Verbruggen F (2020) HG_JUVENILE - Juvenile herring gulls (Larus argentatus, Laridae) hatched and handraised in Ostend (Belgium). Dataset. https://www.movebank.org/cms/webapp?gwt_fragment=page=studies,path=study2217728245

**Comment by ReinoudAllaert** [comment]
Perfect, thanks for checking the description. Updating the citation is no problem. Let me know if there is any other information you need.

**Comment by peterdesmet** [comment]
Great! The study metadata is now ok and the tag data are synced. Next step, see #190.
