### ISSUE TITLE
Republish to IPT

### ISSUE THREAD

**Issue by peterdesmet** [inbo/bird-tracking#198]
## Why

- Some datasets received minor edits to metadata in the IPT (see last updated date > publication date)
- There are new mapping recommendations (https://github.com/inbo/movepub/pull/75 and others)

### zenodo_to_gbif.Rmd

- Set correct copyright holder (see an occurrence record in currently published dataset)
- Set correct contact person/metadata provider (see IPT page in currently published dataset)

### IPT

- Remove current source files (will also remove mapping)
- Upload occurrence + emof
- Verify number of records with currently published dataset
- Map occurrence + emof
- Upload EML
- Manually set:
  - Basic metadata > Publishing org: INBO
  - Basic metadata > Subtype: Observation
  - Basic metadata > Update frequency: annually for living datasets, otherwise not planned
  - Basic metadata > Remove `<span></span>` from last paragraph
  - Citations > Auto-generation: [on](https://github.com/gbif/registry/issues/480#issuecomment-1643882711)
  - Citations > Resource citation identifiers: versioned doi
- Inspect preview
- Publish > Description:
  - For living: Updated DwC mapping with extended measurement or facts + new data
  - For completed: Updated DwC mapping with extended measurement or facts

## Datasets

- [x] BOP_RODENT
- [x] CURLEW_VLAANDEREN
- [x] DELTATRACK
- [x] H_GRONINGEN
- [x] HG_OOSTENDE
- [x] LBBG_ADULT (new dataset, update related links in Zenodo)
- [x] LBBG_JUVENILE
- [x] LBBG_ZEEBRUGGE
- [x] MEDGULL_ANTWERPEN
- [x] MH_ANTWERPEN
- [x] MH_WATERLAND
- [x] O_AMELAND
- [x] O_ASSEN
- [x] O_BALGZAND
- [x] O_SCHIERMONNIKOOG
- [x] O_VLIELAND
- [x] O_WESTERSCHELDE
- [x] SPOONBILL_VLAANDEREN (new dataset, update related links in Zenodo)

**Comment by sannegovaert** [comment]
Done!
