### ISSUE TITLE
Calendar time zone

### ISSUE THREAD

**Issue by bartaelterman** [inbo/bird-tracking#72]
The calendar heatmap shows the data using the timezone of the client's system. Therefore, the result will look different on different systems. The cal-heatmap API itself is timezone agnostic. You cannot set timezones there and so there is no way to prevent this from happening.

This is a example heatmap:

![screen shot 2015-03-23 at 14 15 03](https://cloud.githubusercontent.com/assets/2742677/6780860/059bf8cc-d169-11e4-9540-f99e586b48d8.png)

Here we see the same heatmap with the same data, only the systems timezone was changed:

![screen shot 2015-03-23 at 14 15 11](https://cloud.githubusercontent.com/assets/2742677/6780866/0a7e7964-d169-11e4-9b83-ee87fb2cde2b.png)

I see two options:
1. Convert the data to the appropriate timezone, and document that the results are always displayed in UTC+1 (our local timezone). It's not clean to mess with the data to solve this, but solving this on the display side would mean refactoring or extending the cal-heatmap source code.
2. Do nothing about it but acknowledge that looking at timeseries data has a timezone context which can differ between clients.

Either way, #71 should be fixed.

**Comment by peterdesmet** [comment]
We are sunsetting the `bird tracking explorer` (+ our Carto account only accepts limited API calls). I'm closing any related issues.
